apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cloudnative-pg
  namespace: postgres-operator-poc
spec:
  channel: stable-v1
  installPlanApproval: Manual
  name: cloudnative-pg
  source: certified-operators
  sourceNamespace: openshift-marketplace