apiVersion: v1
kind: Pod
metadata:
  name: quota-test
  namespace: task-generator-dev
spec:
  containers:
    - name: test
      image: nginx
      resources:
        requests:
          cpu: 900m
          memory: 128Mi
        limits:
          cpu: 900m
          memory: 128Mi