frontend:
  ingress:
    enabled: true
  route:
    enabled: false
  securityContext:
    fixedUserEnabled: true
    
postgres:
  envStyle: docker

tasks:
  persistence:
    hostPathEnabled: true
    dynamicEnabled: false
    
    pvName: host-pv-dev
    claimName: host-pvc-dev
    storageClassName: standard
    hostPath: /data/task-generator-dev/tasks

auth:
  containerPort: 80
  service:
    targetPort: 80