platform:
  openshift: true

frontend:
  ingress:
    enabled: false
  route:
    enabled: true
  securityContext:
    fixedUserEnabled: false

postgres:
  envStyle: openshift
  image:
    repository: image-registry.openshift-image-registry.svc:5000/openshift/postgresql
    tag: "15-el9"

tasks:
  persistence:
    hostPathEnabled: false
    dynamicEnabled: true

    claimName: tasks-pvc-dev

auth:
  containerPort: 8080
  service:
    targetPort: 8080