namespace: task-generator-dev

frontend:
  replicas: 1
  image:
    repository: shaykekeidar/kub-demo-frontend
    tag: "latest"
  config:
    FRONTEND_VERSION: "latest"
  ingress:
    host: task-generator-dev.local
    tlsSecretName: frontend-tls
  service:
    port: 80
    targetPort: 80
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  hpa:
    minReplicas: 1
    maxReplicas: 5
    cpuTarget: 50

users:
  replicas: 1
  image:
    repository: shaykekeidar/kub-demo-users
    tag: "latest"
  config:
    USERS_VERSION: "latest"
  service:
    port: 8080
    targetPort: 8080

auth:
  replicas: 1
  image:
    repository: shaykekeidar/kub-demo-auth
    tag: "latest"
  config:
    AUTH_VERSION: "latest"
  service:
    port: 80
    targetPort: 80

tasks:
  replicas: 1
  image:
    repository: shaykekeidar/kub-demo-tasks
    tag: "latest"
  config:
    TASKS_VERSION: "latest"
  service:
    port: 8000
    targetPort: 8000