apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend-deployment

spec:
  replicas: {{ .Values.frontend.replicas }}

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
        - name: frontend

          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"

          env:
            - name: FRONTEND_VERSION
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: FRONTEND_VERSION

          ports:
            - containerPort: 80

          resources:
            requests:
              cpu: {{ .Values.frontend.resources.requests.cpu }}
              memory: {{ .Values.frontend.resources.requests.memory }}

            limits:
              cpu: {{ .Values.frontend.resources.limits.cpu }}
              memory: {{ .Values.frontend.resources.limits.memory }}