apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend-deployment

spec:

  replicas: {{ .Values.frontend.replicas }}

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      serviceAccountName: frontend-sa

      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000

      volumes:
        - name: nginx-cache
          emptyDir: {}
        - name: nginx-run
          emptyDir: {}

      containers:
        - name: frontend

          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"

          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          
          volumeMounts:
            - name: nginx-cache
              mountPath: /var/cache/nginx
            - name: nginx-run
              mountPath: /var/run

          env:
            - name: FRONTEND_VERSION
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: FRONTEND_VERSION

          ports:
            - containerPort: 80

          resources:
            requests:
              cpu: {{ .Values.frontend.resources.requests.cpu }}
              memory: {{ .Values.frontend.resources.requests.memory }}

            limits:
              cpu: {{ .Values.frontend.resources.limits.cpu }}
              memory: {{ .Values.frontend.resources.limits.memory }}