apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.tasks.persistence.claimName }}
spec:
  volumeName: {{ .Values.tasks.persistence.pvName }}
  storageClassName: {{ .Values.tasks.persistence.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.tasks.persistence.storage }}