apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: frontend-read-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    #verbs: ["get", "list", "watch"]
    verbs: [""]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: frontend-read-binding
subjects:
  - kind: ServiceAccount
    name: frontend-sa
    namespace: task-generator-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: frontend-read-role