apiVersion: v1
kind: Service
metadata:
  name: tasks-service
spec:
  type: ClusterIP
  selector:
    app: tasks
  ports:
    - port: {{ .Values.tasks.service.port }}
      targetPort: {{ .Values.tasks.service.targetPort }}