apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deployment
spec:
  replicas: {{ .Values.tasks.replicas }}
  selector:
    matchLabels:
      app: tasks
  template:
    metadata:
      labels:
        app: tasks
    spec:
      containers:
        - name: tasks
          image: "{{ .Values.tasks.image.repository }}:{{ .Values.tasks.image.tag }}"
          ports:
            - containerPort: {{ .Values.tasks.service.targetPort }}
      env:
        - name: TASKS_VERSION
          value: "{{ .Values.tasks.image.tag }}"

        - name: USERS_VERSION
          value: "{{ .Values.users.image.tag }}"

        - name: AUTH_VERSION
          value: "{{ .Values.auth.image.tag }}"

        - name: FRONTEND_VERSION
          value: "{{ .Values.frontend.image.tag }}"