{{- if .Values.tasks.persistence.dynamicEnabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.tasks.persistence.claimName }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.tasks.persistence.storage }}
{{- end }}