apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template: # pod configuration
    metadata:
      labels:
        app: auth
    spec:
      containers: # container configuration
        - name: auth
          image: shaykekeidar/kub-demo-auth:2
          env:
          - name: AUTH_VERSION
            value: "2"




